views/articles.py
from flask import redirect, url_for, render_template, request, session, jsonify
from models import Article, Category, Alert, Comment
from libs import db
from flask import Blueprint
from forms.article_form import CommentForm

article_app = Blueprint('article_app', __name__)


# 根据文章id阅读文章并显示评论功能
@article_app.route('/view/<int:article_id>', methods=['get', 'post'])
def view(article_id):
    article = Article.query.get(article_id)
    if not article:  # 没有找到文章跳到主页
        return redirect(url_for('html'))

    # 只显示最新15条已审核的与文章ID相同的文章评论
    comments = Comment.query.filter(Comment.article_id == article_id).filter(Comment.audited == 1).order_by(
        Comment.time.desc()).limit(15)
    print(comments.count(), '条评论')

    # 发表评论功能，有用户登陆才显示表单
    if 'user' in session:
        form = CommentForm()
        message = {'result': 'fail'}
        if form.validate_on_submit():
            content = form.data['content']
            comment = Comment(
                author=session['user'],
                article_id=article.id,
                content=content
            )
            try:
                db.session.add(comment)
                db.session.commit()
            except Exception as e:
                print(str(e))
            else:
                message = {'result': 'success'}
            return jsonify(message)
        elif form.errors:
            print(form.errors)
            message.update(form.errors)
            return jsonify(message)
        else:
            return render_template('article/detail.html', article=article, comments=comments, form=form)
    return render_template('article/detail.html', article=article, comments=comments)


# 根据文章cate_id显示文章列表
@article_app.route('/cate/<int:cate_id>/<int:page>')
@article_app.route('/', defaults={'cate_id': 0, 'page': 1})
def getArticleList(cate_id, page):
    # 提取最新的公告
    alert = Alert.query.order_by(Alert.alert_id.desc()).first()

    # 提取所有推荐值前15的文章
    recommend_articles = Article.query.filter(Article.is_recommend != None).order_by(Article.is_recommend.desc()).limit(
        15)

    # 导航栏搜索功能
    q = request.args.get('nav_search')
    if request.method == 'GET' and q is not None and q != '':
        print('nav_search', q)
        page = request.args.get('page', 1)
        res = Article.query.filter(Article.content.like('%%%s%%' % q)).order_by(Article.id.desc()).paginate(int(page),
                                                                                                            15)
        articles = res.items
        pageList = res.iter_pages()
        total = res.total
        return render_template('search_articles.html', articles=articles, pageList=pageList, total=total, page=page,
                               q=q, recommend_articles=recommend_articles)

    # 显示分类文章
    if cate_id == 0:
        res = Article.query.order_by(Article.id.desc()).paginate(page, 15)
    else:
        res = Article.query.order_by(Article.id.desc()).filter_by(cate_id=cate_id).paginate(page, 15)
    category = Category.query.get(cate_id)
    articles = res.items
    pageList = res.iter_pages()
    return render_template('article/cate_articles.html', cate_id=cate_id, articles=articles, pageList=pageList,
                           category=category, res=res, alert=alert, recommend_articles=recommend_articles)

views/users.py
from flask import request, redirect, url_for, render_template
from libs import db
from models import User
from flask import Blueprint
from forms.account_form import RegisterForm

user_app = Blueprint("user_app", __name__)


# 用户注册功能
@user_app.route('/register', methods=['get', 'post'])
def register():
    message = None
    form = RegisterForm()
    if form.validate_on_submit():
        if validate_username(request.form['username']):
            return render_template('user/register.html', message='用户名重复')
        realname = request.form['name']
        username = request.form['username']
        password = request.form['password']
        sex = request.form['sex']
        hobby = ', '.join(request.form.getlist('hobby'))
        city = request.form['city']
        intro = request.form['intro']
        user = User(
            realname=realname,
            username=username,
            password=password,
            sex=sex,
            hobby=hobby,
            city=city,
            intro=intro,
        )
        # Hash方式加密原来的密码
        user.hash_password(password)
        try:
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('login'))
        except Exception as e:
            message = '注册失败' + str(e)
    else:
        print(form.errors)
    return render_template('user/register.html', message=message, form=form)


# 验证是否存在同名用户
def validate_username(username):
    return User.query.filter_by(username=username).first()

templates/base.html
<!DOCTYPE html>
<html>
{% block head %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>清心涟漪 - 网页开发项目</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="css/bootstrap.css") }}"/>
        <link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="css/bootstrap-theme.css") }}"/>
        <style type="text/css">
            footer {
                padding: 15px;
                background: #8c8989;
                text-align: center;
            }

            footer nav {
                margin: auto;
                width: 300px;
            }

            .carousel-control.right, .carousel-control.left {
                background-image: none;
            }

            .row {
                margin-top: 15px;
                margin-bottom: 8px;
            }

            .panel {
                margin-top: 15px;
            }

            {% block style %}

            {% endblock %}
        </style>
    </head>
{% endblock %}
<body>
{% block nav %}
    <nav class="navbar navbar-default">
        <div class="container-fluid" style="background-color: #C1F48C;">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">展开导航</span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">清心涟漪</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="/">首页</a></li>
                    {% if cates.total!=0 %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">文章分类 <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                {% for cate in cates %}
                                    <li>
                                        <a href="{{ url_for("article_app.getArticleList", cate_id=cate.cate_id, page=1) }}">{{ cate.cate_name }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endif %}
                </ul>
                <form class="navbar-form navbar-left" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" id="nav_search" name="nav_search"
                               placeholder="根据标题搜索文章">
                    </div>
                    <div class="form-group">
                        <input type="submit" name="search" class="btn btn-default" value="搜索">
                    </div>
                </form>
                {#根据角色和登陆状态不同，显示导航栏右则部分#}
                <ul class="nav navbar-nav navbar-right">
                    {% if not username %}
                        <li><a href="{{ url_for("login") }}">登陆</a></li>
                        <li><a href="{{ url_for("user_app.register") }}">注册</a></li>
                    {% else %}
                        {% if username=='admin' %}
                            <li><a href="{{ url_for("admin_app.admin_index") }}">{{ username }}管理后台</a></li>
                            <li><a href="{{ url_for("logout") }}">登出</a></li>
                        {% else %}
                            <li><a href="{{ url_for("member_app.member_index") }}">{{ username }}会员中心</a></li>
                            <li><a href="{{ url_for("logout") }}">登出</a></li>
                        {% endif %}
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
{% endblock %}

{% block content %}
    每个页面不同部分
{% endblock %}

{% block footer %}
    <footer>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    Copyright 2007 - 2020 Articuly | All Rights Reserved | Powered by Bootstrap & Flask
                </div>
            </div>
        </div>
        <nav>
            <ul class="nav nav-pills">
                <li><a href="" data-toggle="modal" data-target="#myModal">隐私政策</a></li>
                <li><a href="https://articuly.com" target="_blank">作者博客</a></li>
                <li><a href="">给我留言</a></li>
            </ul>
        </nav>
        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h3 class="modal-title" id="myModalLabel"><b>隐私政策</b>
                        </h3>
                    </div>
                    <div class="modal-body">
                        <h4><b>我们是谁</b></h4>
                        <p class="text-left">我是一名独立博客的博主、Python全栈工程师。</p>
                        <p class="text-left">我的站点地址是：https://articuly.com。</p>
                        <h4><b>我们收集何种数据</b></h4>
                        <p class="text-left"><i>评论：</i>当访客留下评论时，我们会收集评论表单所显示的数据，和访客的IP地址及浏览器的user
                            agent字符串来帮助检查垃圾评论。由您的电子邮件地址所生成的匿名化字符串（又称为哈希）可能会被提供给Gravatar服务确认您是否有使用该服务。</p>
                        <p class="text-left"><i>媒体：</i>如果您向此网站上传图片，您应当避免上传那些有嵌入地理位置信息（EXIF
                            GPS）的图片。此网站的访客将可以下载并提取此网站的图片中的位置信息。</p>
                        <p class="text-left"><i>联系表单：</i>建议使用电子邮件来联系此站管理员。</p>
                        <p class="text-left"><i>Cookies：</i>如果您在我们的站点上留下评论，您可以选择用cookies保存您的姓名、电子邮件地址和网站。这是通过让您可以不用在评论时再次填写相关内容而向您提供方便。这些cookies会保留一年。如果您编辑或发布文章，我们会在您的浏览器中保存一个额外的cookie。这个cookie不包含个人数据而只记录了您刚才编辑的文章的ID。这个cookie会保留一天。
                        </p>
                        <p class="text-left"><i>统计：</i>此站点使用Google Analytics和百度统计。</p>
                        <h4><b>我们与谁共享您的信息</b></h4>
                        <p class="text-left">我们不与其他任何人共享您的信息。</p>
                        <h4><b>我们保留多久您的信息</b></h4>
                        <p class="text-left">如果您留下评论，评论和其元数据将被无限期保存。我们这样做以便能识别并自动批准任何后续评论，而不用将这些后续评论加入待审队列。</p>
                        <p class="text-left">
                            对于本网站的注册用户，我们也会保存用户在个人资料中提供的个人信息。所有用户可以在任何时候查看、编辑或删除他们的个人信息（除了不能变更用户名外）、站点管理员也可以查看及编辑那些信息。</p>
                        <h4><b>您对您的信息有什么权利</b></h4>
                        <p class="text-left">
                            如果您有此站点的账户，或曾经留下评论，您可以请求我们提供我们所拥有的您的个人数据的导出文件，这也包括了所有您提供给我们的数据。您也可以要求我们抹除所有关于您的个人数据。这不包括我们因管理、法规或安全需要而必须保留的数据。</p>
                        <h4><b>我们将您的信息发送到哪</b></h4>
                        <p class="text-left">访客评论可能会被自动垃圾评论监测服务检查。</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">我已知悉</button>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script type="text/javascript" src="{{ url_for("static", filename="js/jquery-3.4.1.min.js") }}"></script>
    <script type="text/javascript" src="{{ url_for("static", filename="js/bootstrap.min.js") }}"></script>
{% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}
<!DOCTYPE html>
<html>
<body>
{% block content %}
    <main>
        <div id="myCarousel" class="carousel slide">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <!-- 旋转木马项目 -->
            <div class="carousel-inner">
                <div class="active item"><img src="{{ url_for('static', filename='img/star-player.jpg') }}" width="80%"
                                              class="img-responsive center-block"></div>
                <div class="item"><img src="{{ url_for('static', filename='img/love.jpg') }}" width="80%"
                                       class="img-responsive center-block">
                </div>
                <div class="item"><img src="{{ url_for('static', filename='img/mobile.jpg') }}" width="80%"
                                       class="img-responsive center-block">
                </div>
            </div>
            <!-- 旋转木马导航 -->
            <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
            <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 col-md-offset-1 col-sm-7 col-sm-offset-1">
                    <div class="alert alert-info" role="alert">{{ alert.alert_content }}</div>
                    <div class="jumbotron">
                        <h1>Hello, python!</h1>
                        <p>
                            Python是用来编写应用程序的高级编程语言，它“优雅”、“明确”、“简单”。Python就为我们提供了非常完善的基础代码库。人工智能、大数据、数据分析、网站项目等领域的开发编程都可使用Python完成。</p>
                        <p><a class="btn btn-primary btn-lg" href="#" role="button">立即报名学习</a></p>
                    </div>
                    {#                    {% for article in articles %}#}
                    {#                        <div class="list-group">#}
                    {#                            <a href="{{ url_for('article_app.view', article_id=article.id) }}" class="list-group-item">#}
                    {#                                <h4 class="list-group-item-heading">{{ article.title }}</h4>#}
                    {#                                <p class="list-group-item-text">{{ article.intro }}</p>#}
                    {#                            </a>#}
                    {#                        </div>#}
                    {#                    {% endfor %}#}
                    <ul class="media-list">
                        {% for article in articles %}
                            <li class="media">
                                <div class="pull-left">
                                    {# 缩略图为空则显示默认图片，否则显示上传的缩略图 #}
                                    {% if article.thumb==None or article.thumb=="" %}
                                        <img src="{{ url_for('static', filename='img/side/articuly.jpg') }}"
                                             class="media-object" style="width: 120px; height: 120px;">
                                    {% else %}
                                        <img src="{{ article.thumb }}" class="media-object"
                                             style="width: 120px; height: 120px;">
                                    {% endif %}
                                </div>
                                <div class="media-body">
                                    <h2 class="media-heading"><a
                                            href="{{ url_for("article_app.view", article_id=article.id) }}">{{ article.title }}</a>
                                    </h2>
                                    <div class="media">
                                        <p>{{ article['intro'] }}</p>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            {# 如果有前一页、后一页，则显示前后一页的翻页跳转，需要分页对象传到前端 #}
                            {% if res.has_prev %}
                                <li>
                                    <a href="{{ url_for('html', page=res.prev_num ) }}" aria-label="Next">
                                        <span aria-hidden="true">上一页</span></a>
                                </li>
                            {% endif %}
                            {% for page in pageList %}
                                {% if page!=None %}
                                    <li><a href="{{ url_for('html', page=page) }}">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="#">...</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if res.has_next %}
                                <li>
                                    <a href="{{ url_for('html', page=res.next_num ) }}" aria-label="Next">
                                        <span aria-hidden="true">下一页</span></a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
                <div class="col-md-4 col-sm-3">
                    <img src="{{ url_for('static', filename='img/side/articuly.jpg') }}" alt="清心涟漪" class="img-circle">
                    <img src="{{ url_for('static', filename='img/side/ad.jpg') }}" alt="" class="img-rounded">
                    <img src="{{ url_for('static', filename='img/side/rainbow.jpg') }}" alt="彩虹" class="img-circle">
                    <img src="{{ url_for('static', filename='img/side/ad.jpg') }}" alt="" class="img-rounded">
                    <img src="{{ url_for('static', filename='img/side/github.jpg') }}" alt="Github" class="img-circle">
                    <img src="{{ url_for('static', filename='img/side/ad.jpg') }}" class="img-rounded">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">热门文章：</h3>
                        </div>
                        <div class="panel-body">
                            <ul class="list-group">
                                {% for article in recommend_articles %}
                                    <li class="list-group-item"><a
                                            href="{{ url_for('article_app.view', article_id=article.id) }}">{{ article.title }}</a>
                                        <span class="badge">{{ article.is_recommend }}</span></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">搜索博客：</h3>
                        </div>
                        <div class="panel-body">
                            <form class="form-inline" id="search2">
                                <input type="text" class="form-control" placeholder="Python">
                                <button type="submit" class="btn btn-default">搜索</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}
</body>
</html>

templates/login.html
{% extends "base.html" %}
<!DOCTYPE html>
<html>
<body>
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="main col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
                <h2 class="text-center"><b>登陆</b></h2>
                {% if message %}
                    <div class="alert alert-info" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
                {#                <form action="" method="post" class="form-horizontal">#}
                {#                    <div class="form-group">#}
                {#                        <label for="username" class="control-label">用户名：</label>#}
                {#                        <input type="text" class="form-control" name="username" id="username"#}
                {#                               placeholder="请填写您的用户名">#}
                {#                    </div>#}
                {#                    <div class="form-group">#}
                {#                        <label for="password" class="control-label">密码：</label>#}
                {#                        <input type="password" class="form-control" name="password" id="password"#}
                {#                               placeholder="请设置您的密码">#}
                {#                    </div>#}
                {#                    <div class="form-group">#}
                {#                        <div class="text-right">#}
                {#                            <input type="submit" class="btn btn-default" name="submit" id="btn1" value="立即登陆">#}
                {#                        </div>#}
                {#                    </div>#}
                {#                </form>#}
                <form action="" method="post" class="form-horizontal">
                    {% for field in form %}
                        {% if field.widget.input_type!="hidden" %}
                            <div class="form-group">
                                {{ field.label(class="control-label") }}
                                {{ field }}
                                {# 如果发生表单类数据验证错误则在前端提示 #}
                                {% if field.errors %}
                                    <div class="alert alert-warning alert-dismissable" role="alert">
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span></button>
                                        <strong>注意! </strong>
                                        {{ field.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

templates/search_articles.html
{% extends "base.html" %}
<!DOCTYPE html>
<html>
{# 使用导航栏搜索框搜索后渲染的模板 #}
<body>
{% block content %}
    <main>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 col-md-offset-1 col-sm-7 col-sm-offset-1">
                    {% if total!=0 %}
                        <div class="alert alert-info" role="alert">找到{{ total }}篇文章符合您搜索的条件</div>
                    {% else %}
                        <div class="alert alert-info" role="alert">没有找到符合您搜索条件的文章</div>
                    {% endif %}
                    <ul class="media-list">
                        {% for article in articles %}
                            <li class="media">
                                <div class="pull-left">
                                    {% if article.thumb==None or article.thumb=="" %}
                                        <img src="{{ url_for('static', filename='img/side/articuly.jpg') }}"
                                             class="media-object" style="width: 120px; height: 120px;">
                                    {% else %}
                                        <img src="{{ article.thumb }}" class="media-object"
                                             style="width: 120px; height: 120px;">
                                    {% endif %}
                                </div>
                                <div class="media-body">
                                    <h2 class="media-heading"><a
                                            href="{{ url_for("article_app.view", article_id=article.id) }}">{{ article.title }}</a>
                                    </h2>
                                    <div class="media">
                                        <p>{{ article['intro'] }}</p>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            {% for page in pageList %}
                                {% if page!=None %}
                                    <li><a href="?page={{ page }}&nav_search={{ q }}">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="#">...</a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </nav>
                </div>
                <div class="col-md-4 col-sm-3">
                    <img src="{{ url_for('static', filename='img/side/articuly.jpg') }}" alt="清心涟漪" class="img-circle">
                    <img src="{{ url_for('static', filename='img/side/ad.jpg') }}" alt="" class="img-rounded">
                    <img src="{{ url_for('static', filename='img/side/rainbow.jpg') }}" alt="彩虹" class="img-circle">
                    <img src="{{ url_for('static', filename='img/side/ad.jpg') }}" alt="" class="img-rounded">
                    <img src="{{ url_for('static', filename='img/side/github.jpg') }}" alt="Github" class="img-circle">
                    <img src="{{ url_for('static', filename='img/side/ad.jpg') }}" class="img-rounded">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">热门文章：</h3>
                        </div>
                        <div class="panel-body">
                            <ul class="list-group">
                                {% for article in recommend_articles %}
                                    <li class="list-group-item"><a
                                            href="{{ url_for('article_app.view', article_id=article.id) }}">{{ article.title }}</a>
                                        <span class="badge">{{ article.is_recommend }}</span></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">搜索博客：</h3>
                        </div>
                        <div class="panel-body">
                            <form class="form-inline" id="search2">
                                <input type="text" class="form-control" placeholder="Python">
                                <button type="submit" class="btn btn-default">搜索</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}
</body>
</html>